Basic Data Scaling

In [8]:
import numpy as np
M = np.array([
    [10, 200, 3000],
    [12, 190, 4000],
    [11, 210, 3500]
])
print("M:\n", M)

M:
 [[  10  200 3000]
 [  12  190 4000]
 [  11  210 3500]]


Mean & Standard Deviation

In [9]:
mean = np.mean(M, axis=0)
std_dev = np.std(M, axis=0)
print("\nMean:\n", mean)
print("\nStandard Deviation:\n", std_dev)



Mean:
 [  11.  200. 3500.]

Standard Deviation:
 [  0.81649658   8.16496581 408.24829046]


Scale: subtract mean, then divide by std

In [10]:
M_scaled = (M - mean) / std_dev
print("\nScaled matrix (each feature now has mean 0 and std 1):\n", M_scaled)


Scaled matrix (each feature now has mean 0 and std 1):
 [[-1.22474487  0.         -1.22474487]
 [ 1.22474487 -1.22474487  1.22474487]
 [ 0.          1.22474487  0.        ]]


In [11]:
print("\nCheck means after scaling (should be ~0):", M_scaled.mean(axis=0))
print("Check stds after scaling (should be ~1):", M_scaled.std(axis=0))


Check means after scaling (should be ~0): [0. 0. 0.]
Check stds after scaling (should be ~1): [1. 1. 1.]
