From Data to Matrix

Create Raw Data:

In [38]:
import numpy as np

Student_grades = [
    ['Shyam', 97, 95],
    ['Ram', 91, 92],
    ['Sita', 85, 87]    
    ]

names = [row[0] for row in Student_grades]
scores = [row [1:] for row in Student_grades]

Convert to Matrix:

In [39]:
score_matrix = np.array(scores)
print("Original score matrix:")
print(score_matrix)

Original score matrix:
[[97 95]
 [91 92]
 [85 87]]


Add a new feature:

In [40]:
sports_score = np.array([88, 92, 79]).reshape(-1, 1)

Overall_matrix = np.hstack((score_matrix, sports_score))
print("\nAfter adding sports_score column:")
print(Overall_matrix)


After adding sports_score column:
[[97 95 88]
 [91 92 92]
 [85 87 79]]


Calculate a new feature:

In [41]:
average_score = Overall_matrix.mean(axis=1).reshape(-1, 1)
avg_matrix = np.hstack((Overall_matrix, average_score))
print("\nAfter adding average_score column:\n", avg_matrix)


After adding average_score column:
 [[97.         95.         88.         93.33333333]
 [91.         92.         92.         91.66666667]
 [85.         87.         79.         83.66666667]]


Scale a feature:

In [42]:
scaled_matrix = avg_matrix.copy()
scaled_matrix[:,0] = scaled_matrix[:,0] * 1.1
print("\nAfter scaling math_score by factor 1.1:")
print(scaled_matrix)


After scaling math_score by factor 1.1:
[[106.7         95.          88.          93.33333333]
 [100.1         92.          92.          91.66666667]
 [ 93.5         87.          79.          83.66666667]]


In [43]:
print("\nNames with final data:")
for name, row in zip(names, scaled_matrix):
    print(f"{name}: {row}")


Names with final data:
Shyam: [106.7         95.          88.          93.33333333]
Ram: [100.1         92.          92.          91.66666667]
Sita: [93.5        87.         79.         83.66666667]
